import { palette } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const registerStyles = StyleSheet.create({
  root: {
    flex: 1,
    width: "100%",
  },
  inner: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 20,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  backBtn: { paddingVertical: 4, width: 72 },
  backText: { color: "rgba(255,255,255,0.85)", fontSize: 15 },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
  },
  headerTitle: {
    fontSize: 12,
    letterSpacing: 3,
    color: "rgba(255,255,255,0.9)",
    fontWeight: "800",
  },
  progressRow: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 8,
  },
  progressSeg: {
    flex: 1,
    height: 4,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  progressSegOn: {
    backgroundColor: palette.accent,
  },
  scroll: { flex: 1 },
  scrollContent: {
    paddingBottom: 120,
    gap: 14,
    flexGrow: 0,
    justifyContent: "flex-start",
    alignItems: "stretch",
  },
  error: { color: "tomato", marginBottom: 4 },
  errorBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(220, 60, 60, 0.18)",
    borderWidth: 1,
    borderColor: "rgba(255, 120, 120, 0.45)",
    marginTop: 4,
  },
  errorBannerTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "rgba(255, 200, 200, 0.98)",
  },
  errorBannerBody: {
    fontSize: 14,
    lineHeight: 20,
    color: "rgba(255, 230, 230, 0.92)",
  },
  errorBannerCompact: {
    marginBottom: 8,
  },
  eyebrow: { letterSpacing: 2, fontSize: 12, marginTop: 4 },
  introTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "rgba(255,255,255,0.96)",
    marginTop: 6,
  },
  introBody: { fontSize: 15, lineHeight: 22, marginTop: 10 },
  stepsCard: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    padding: 16,
    gap: 14,
    marginTop: 8,
  },
  stepRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  stepNum: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  stepNumText: { fontWeight: "800", color: "rgba(255,255,255,0.9)" },
  stepLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: "rgba(255,255,255,0.92)",
  },
  accentEyebrow: {
    color: palette.accent,
    fontSize: 11,
    letterSpacing: 2,
    fontWeight: "800",
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "rgba(255,255,255,0.95)",
    letterSpacing: 0.5,
  },
  sectionHint: { fontSize: 14, lineHeight: 20 },
  slotTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "rgba(255,255,255,0.95)",
    marginTop: 8,
  },
  slotHint: { fontSize: 14, lineHeight: 20, marginTop: 4 },
  preview: {
    marginTop: 12,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    minHeight: 220,
    position: "relative",
  },
  previewImage: { width: "100%", height: 240, resizeMode: "cover" },
  previewPlaceholder: {
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  previewLabel: { fontSize: 11, letterSpacing: 2 },
  checkBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: palette.success,
    alignItems: "center",
    justifyContent: "center",
  },
  captureBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: palette.accent,
    borderRadius: 999,
    minHeight: 54,
    paddingHorizontal: 20,
  },
  captureBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  thumbRow: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "center",
    marginTop: 8,
  },
  thumb: {
    position: "relative",
    width: 72,
    height: 72,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.12)",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  thumbActive: {
    borderColor: palette.accent,
  },
  thumbImage: { width: "100%", height: "100%" },
  thumbEmpty: { fontSize: 18, fontWeight: "800" },
  thumbCheck: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: palette.success,
    alignItems: "center",
    justifyContent: "center",
  },
  qualityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    paddingVertical: 8,
  },
  qualityLabel: {
    flex: 1,
    fontSize: 14,
    color: "rgba(255,255,255,0.85)",
    paddingRight: 12,
  },
  analyzeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: palette.accent,
    borderRadius: 999,
    minHeight: 54,
    marginTop: 8,
  },
  analyzeBtnDisabled: {
    opacity: 0.4,
  },
  formGap: { gap: 16, marginTop: 8 },
  notesLabel: {
    letterSpacing: 2,
    fontSize: 12,
    color: "rgba(255,255,255,0.88)",
  },
  notesInput: {
    minHeight: 100,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.38)",
    backgroundColor: "rgba(255,255,255,0.10)",
    paddingHorizontal: 16,
    paddingVertical: 12,
    color: "rgba(255,255,255,0.98)",
    fontSize: 17,
    textAlignVertical: "top",
  },
  summaryCard: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    padding: 16,
    gap: 12,
    marginTop: 8,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "flex-start",
  },
  summaryLabel: {
    fontSize: 10,
    letterSpacing: 1.4,
    width: 120,
  },
  summaryValue: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: "rgba(255,255,255,0.92)",
    textAlign: "right",
  },
  patchHint: { fontSize: 13, lineHeight: 18, marginTop: 4 },
  confirmBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: palette.accent,
    borderRadius: 999,
    minHeight: 54,
    marginTop: 16,
  },
  confirmBtnDisabled: {
    opacity: 0.35,
  },
});
